
version: '3'

services:
   neuraldigest-classification-etl:
        # this is for allowing to run in detached mode
        tty: true
        stdin_open: true
        build:
            context: ./
            dockerfile: docker/neuraldigest-classification-etl.Dockerfile
        image: liamwazherealso/neuraldigest-classification-etl
        container_name: neuraldigest-classification-etl
        volumes:
            - ./dist:/app/dist
