# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-arm64/ca-certificates-2023.01.10-hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libcxx-14.0.6-h848a8c0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libffi-3.4.2-hca03da5_6.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ncurses-6.4-h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/xz-5.2.10-h80987f9_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/yaml-0.2.5-h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/zlib-1.2.13-h5a0b063_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/openssl-1.1.1t-h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/readline-8.2-h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tk-8.6.12-hb8d0fd4_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/sqlite-3.41.1-h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/python-3.9.16-hc0d8a6c_2.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/certifi-2022.12.7-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/cfgv-3.3.1-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/distlib-0.3.6-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/filelock-3.9.0-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/platformdirs-2.5.2-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pyyaml-6.0-py39h80987f9_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/wheel-0.38.4-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/cffi-1.15.1-py39h80987f9_3.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/setuptools-65.6.3-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/virtualenv-20.17.1-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nodeenv-1.7.0-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pip-23.0.1-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ukkonen-1.0.1-py39h525c30c_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/identify-2.5.5-py39hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pre-commit-3.2.1-py39hca03da5_0.conda
